# Docker Compose 파일 - 현재 실행중인 컨테이너에서 생성된 이미지 사용
version: "2.2"
services:
  ubuntu:
    container_name: ubuntu-desktop-port
    image: oseongryu/ubuntu-desktop:with-ports
    ports:
      - "13386:3389"
      - "18000:8000"
      - "18001:8001"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
