# Docker Compose 파일 포맷 버전 지정
version: "2.2"

services:
  mysql:
    container_name: db-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    build:
      context: ./
      dockerfile: Dockerfile
    image: db/mysql:8.0.38
    environment:
      - LC_ALL=C.UTF-8
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=mysqldb
    ports:
      - "3306:3306"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
    restart: always
