# Docker Compose 파일 포맷 버전 지정
version: "2.2"

services:
  mysql:
    container_name: db-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    build:
      context: ./
      dockerfile: Dockerfile
    image: db/mysql:8.0.38
    environment:
      - LC_ALL=C.UTF-8
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
    restart: always
  mongodb:
    container_name: db-mongodb
    build:
      context: ./mongodb/
      dockerfile: Dockerfile
    image: db/mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testdb
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=db
    ports:
      - "27017:27017"
    stdin_open: true # docker run -i
    tty: true # docker run -t
  redis:
    container_name: db-redis
    build:
      context: ./redis/
      dockerfile: Dockerfile
    image: db/redis:latest
    ports:
      - "6379:6379"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
