version: "2.2"
services:
  cli:
    container_name: cli-2004
    build:
      context: ./cli-2004/
      dockerfile: Dockerfile
    image: oseongryu/cli-2004:1.0.0
    ports:
      - "13000:3000"
      - "18091:8091"
    volumes:
      - ~/git:/git
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
  gui:
    container_name: gui-2004
    build:
      context: ./gui-2004/
      dockerfile: Dockerfile
    image: oseongryu/gui-2004:1.0.0
    ports:
      - "13389:3389"
      - "13000:3000"
    volumes:
      - ~/git:/git
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
  gui-2404:
    container_name: gui-2404
    build:
      context: ./gui-2404/
      dockerfile: Dockerfile
    image: oseongryu/gui-2404:1.0.0
    ports:
      - "13387:3389"
      - "13000:3000"
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true
